# Chapter 1. PyTorchの基本

## Tensorの扱い

#### 生成とindexによる代入と抽出

In [1]:
import numpy as np
import torch

In [3]:
t = torch.tensor([[1,2],[3,4]])
print(t)

tensor([[1, 2],
        [3, 4]])


In [7]:
t = torch.arange(0,10)
print(t)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [12]:
t = torch.randn(10, 5)
print(t)

tensor([[-1.5210, -1.4773,  0.7581, -0.2474, -2.5261],
        [-0.6151, -0.4940, -0.4101,  0.7513, -0.7408],
        [ 0.3151,  1.3492, -1.9902,  0.2413, -0.8299],
        [ 0.3276,  0.1121,  0.1326,  0.1444,  0.2699],
        [ 1.1167, -1.0587,  0.5871,  0.2814,  1.1776],
        [-0.3473,  0.2123, -0.3058,  0.1901,  1.6929],
        [ 0.2764, -0.0329, -0.7182,  0.4316, -0.1645],
        [ 0.6947,  2.0871,  0.0699,  0.1656,  0.7212],
        [ 0.0854,  0.3429, -1.3672,  0.5432,  0.1347],
        [-0.4319, -0.7617,  0.9607, -0.1380,  0.8157]])


In [13]:
x = t.numpy()

In [21]:
print(t[:, [1,2]])
t[3] = 10
t[:, 1] = 20
print(t)

tensor([[-1.4773,  0.7581],
        [-0.4940, -0.4101],
        [ 1.3492, -1.9902],
        [10.0000, 10.0000],
        [-1.0587,  0.5871],
        [ 0.2123, -0.3058],
        [-0.0329, -0.7182],
        [ 2.0871,  0.0699],
        [ 0.3429, -1.3672],
        [-0.7617,  0.9607]])
tensor([[-1.5210, 20.0000,  0.7581, -0.2474, -2.5261],
        [-0.6151, 20.0000, -0.4101,  0.7513, -0.7408],
        [ 0.3151, 20.0000, -1.9902,  0.2413, -0.8299],
        [10.0000, 20.0000, 10.0000, 10.0000, 10.0000],
        [ 1.1167, 20.0000,  0.5871,  0.2814,  1.1776],
        [-0.3473, 20.0000, -0.3058,  0.1901,  1.6929],
        [ 0.2764, 20.0000, -0.7182,  0.4316, -0.1645],
        [ 0.6947, 20.0000,  0.0699,  0.1656,  0.7212],
        [ 0.0854, 20.0000, -1.3672,  0.5432,  0.1347],
        [-0.4319, 20.0000,  0.9607, -0.1380,  0.8157]])


#### 演算